language: node_js
cache:
  directories:
    - ~/.npm
    - node_modules/

branches:
  only:
    - master

before_script:
  - cd app
  - npm install

jobs:
  include:
    - node_js: 8
      script:
        - npm run test
    - node_js: 10
      script:
        - npm run test
    - node_js: 13
      script:
        - npm run test
        - npm run coveralls
        - npm run codacy
