"use strict";

module.exports = Object.freeze({
  REQUESTED_CHANGES: "REQUESTED_CHANGES",
  APPROVED: "APPROVED",
  STATUS_UNKNOWN: "UNKNOWN",
  STATUS_MERGEABLE: "MERGEABLE",
  STATUS_UNMERGEABLE: "UNMERGEABLE",
  STATUS_CONFLICTING: "CONFLICTING",
  STATE_OPEN: "OPEN",
  STATE_CLOSED: "CLOSED",
  STATE_UNKNOWN: "NULL",
  REBASE_NEEDED: "rebase_needed",
  REVIEW_NEEDED: "review_needed",
  CHECKS_SUCCESS_CONCLUSION: "success",
  MAX_DAYS_ALLOWED_FOR_COMMIT: 3,
  HTTP_CODE_MERGE_SUCCESS: 200,
  HTTP_CODE_NOT_MERGEABLE: 405,
  HTTP_CODE_BASE_OR_HEAD_NOT_FOUND: 404,
  HTTP_CODE_CONFLICT: 409,
});



